CREATE TABLE ROLE (
  ID bigint(20) NOT NULL,
  NAME varchar(255) DEFAULT NULL,
  PRIMARY KEY (ID)
) ;

CREATE TABLE USER (
   id  bigint(20) NOT NULL,
   firstname  varchar(255) DEFAULT NULL,
   lastname  varchar(255) DEFAULT NULL,
   password  varchar(255) DEFAULT NULL,
   username  varchar(255) DEFAULT NULL,
  PRIMARY KEY ( id )
) ;

CREATE TABLE  user_credential  (
   USER_ID  int(11) NOT NULL,
   PASSWORD  varchar(255) NOT NULL DEFAULT 'welcome',
   ENABLE  int(11) NOT NULL DEFAULT '0',
   Role_Name  varchar(45) DEFAULT NULL,
   change_password  int(1) DEFAULT NULL,
  PRIMARY KEY ( USER_ID )
) ;

CREATE TABLE  user_details  (
   user_id  int(11) NOT NULL,
   sales_execode  varchar(5) DEFAULT NULL,
   description  varchar(45) DEFAULT NULL,
   name  varchar(45) DEFAULT NULL,
   phone  bigint(10) DEFAULT NULL,
   email  varchar(45) DEFAULT NULL,
   role_name  varchar(25) NOT NULL,
   managerID  int(11) NOT NULL,
   alternative_emp  int(11) DEFAULT NULL,
   active_flag  int(11) DEFAULT NULL,
   next_approver  int(11) NOT NULL,
  PRIMARY KEY ( user_id )
);

CREATE TABLE  user_role  (
   user_id  bigint(20) NOT NULL,
   role_id  bigint(20) NOT NULL,
  PRIMARY KEY ( user_id , role_id ),
  CONSTRAINT  FK_USER_ROLE_USER FOREIGN KEY ( user_id ) REFERENCES  USER  ( id ),
  CONSTRAINT  FK_USER_ROLE_ROLE FOREIGN KEY ( role_id ) REFERENCES  role  ( id )
) ;

CREATE TABLE  user_roles  (
   ID  int(11) NOT NULL,
   ROLE_NAME  varchar(25) NOT NULL DEFAULT '',
  PRIMARY KEY ( ROLE_NAME )
) ;

create table account_master (
    ID bigint generated by default as identity, 
    alias VARCHAR(255), 
    billingaddress varchar(255), 
    code varchar(255), 
    contactperson varchar(255), 
    contactpersonemailid varchar(255), 
    contactpersonmobilenumber varchar(255), 
    deliveryaddress varchar(255), 
    emailid varchar(255), 
    locality varchar(255), 
    name varchar(255), 
    pannumber varchar(255), 
    phonenumber varchar(255), 
    state varchar(255), 
    tin varchar(255), 
    typeofcustomer varchar(255),
     primary key (ID)
) ;

create table department_master (
    id bigint generated by default as identity, 
    alias varchar(255), 
    code varchar(255), 
    name varchar(255), 
    primary key (id)
);

create table employee_master (
    id bigint generated by default as identity, 
    alias varchar(255), 
    code varchar(255), 
    date_of_joining varchar(255), 
    department_code varchar(255), 
    name varchar(255), 
    photo_attachment varchar(255), 
    proof_attachment varchar(255), 
    primary key (id)
);

create table product_master (
    id bigint generated by default as identity, 
    alias varchar(255), 
    buying_price double, 
    code varchar(255), 
    name varchar(255), 
    reorder_level varchar(255), 
    selling_price double, 
    uom varchar(255), 
    primary key (id)
);

create table section_master (
    id bigint generated by default as identity, 
    alias varchar(255), 
    code varchar(255), 
    name varchar(255), 
    primary key (id)
);

create table tank_operation_dailytankfeeding (
    dailytankfeeding_id bigint generated by default as identity, 
    consumed_percentage double, 
    feed_name varchar(255), 
    feed_quantity double, 
    medicine_name varchar(255), 
    medicine_quantity double, 
    medicine_timings varchar(255), 
    dailytankrecording_id bigint not null, 
    primary key (dailytankfeeding_id)
);

create table tank_operation_dailytankrecording (
    dailytankrecording_id bigint generated by default as identity, 
    do_number integer, 
    doc bigint, 
    document_date varchar(255), 
    labreport_attachment varchar(255), 
    mortality varchar(255), 
    pham varchar(255), 
    phpm varchar(255), 
    remarks varchar(255), 
    site_name varchar(255), 
    supervisor varchar(255), 
    tank_name varchar(255), 
    primary key (dailytankrecording_id)
);

create table warehouse_master (
    id bigint generated by default as identity, 
    alias varchar(255), 
    code varchar(255), 
    name varchar(255), 
    primary key (id)
);

alter table account_master add constraint UKhquix0g8mpv8do9fkn35vnw1s unique (code);
alter table department_master add constraint UK_96llu7lrwu7yx0kqfpvff2e5o unique (code);
alter table employee_master add constraint UK_hsd6xp43qewvsqo4n207qfg84 unique (code);
alter table product_master add constraint UK_h1xwua5w7klvas548yy024yfk unique (code);
alter table section_master add constraint UK_orn1albttsvekpb0sffrd1o2j unique (code);
alter table warehouse_master add constraint UK_jx0mykrxjtk9k9t262d1dt5kr unique (code);
alter table tank_operation_dailytankfeeding add constraint FKox5uym69mtq06xwga947x2fw7 foreign key (dailytankrecording_id) references tank_operation_dailytankrecording;

